### ISSUE TITLE
Error: Request Lets Encrypt Certificate

### ISSUE THREAD

**Issue by broros** [virtualmin/virtualmin-gpl#140]
I just installed this on Debian 10... but I think lets Encrypt is not installed when I ran the installation script.

<urlopen error [Errno -2] Name or service not known>

```
Traceback (most recent call last):
  File "/usr/share/webmin/webmin/acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "/usr/share/webmin/webmin/acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact)
  File "/usr/share/webmin/webmin/acme_tiny.py", line 143, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to /home/revelhost/public_html/.well-known/acme-challenge/12XPFKosOpR16X7basq1ERL_pgqm8yTBTxvFneg4v2Q, but couldn't download http://autoconfig.revelhost.net/.well-known/acme-challenge/12XPFKosOpR16X7basq1ERL_pgqm8yTBTxvFneg4v2Q: Error:
Url: http://autoconfig.revelhost.net/.well-known/acme-challenge/12XPFKosOpR16X7basq1ERL_pgqm8yTBTxvFneg4v2Q
Data: None
Response Code: None
Response: <urlopen error [Errno -2] Name or service not known>

```

**Comment by jcameron** [comment]
Looks like the issue is that the test file couldn't be downloaded by the let's encrypt service. Try removing `autoconfig.revelhost.net` from the list of hostnames to request a cert for.

**Comment by broros** [comment]
lets-encrypt was not installed,  maybe because I installed Webmin first using the deb package then after that I installed Virtualmin with the script

I think this means that let's encrypt is not installed
<urlopen error [Errno -2] Name or service not known>

**Comment by rostovtsev** [comment]
> .. lets-encrypt was not installed..

Do you mean `certbot` package?
